server:
   port: 8080
      
spring:
  application:
    name: Zuul-Gateway
    
zuul:
   routes:
      userService:
         url: http://user-service
      flightService:
         serviceId: Flights-Registry-Service
      bookingService:
         serviceId: passenger-booking-service

eureka:
  instance:
    hostname: localhost

